---
- name: create tomcat service file
  template:
    src: /ans5/templates/tomcatservice.j2
    dest: /etc/systemd/system/tomcat.service

- name: reload deamon service
  systemd:
    daemon_reload: yes

- name: start tomcat
  systemd:
    name: tomcat
    state: started

